# This file was generated by GoReleaser. DO NOT EDIT.
class IconPlugin < Formula
  desc "Development tooling for InsightConnect plugins"
  homepage "https://rapid7.com"
  version "3.3.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rapid7/icon-plugin-homebrew/releases/download/v3.3.1/icon-plugin_3.3.1_Darwin_x86_64.tar.gz"
    sha256 "431f35ef403f36d9a8496d1c56d0c2e7bac56050971509a5e829c9996335c709"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rapid7/icon-plugin-homebrew/releases/download/v3.3.1/icon-plugin_3.3.1_Linux_x86_64.tar.gz"
      sha256 "64f320ced635b049ea3e286adc2134f5adf43cf347b7ae66bf9eb7f7ccb07cb4"
    end
  end

  def install
    bin.install "icon-plugin"
  end

  test do
    system "#{bin}/icon-plugin --version"
  end
end
