# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IconPlugin < Formula
  desc "Development tooling for InsightConnect plugins"
  homepage "https://rapid7.com"
  version "v4.11.6"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rapid7/icon-plugin-homebrew/releases/download/v4.11.6/icon-plugin_v4.11.6_Darwin_x86_64.tar.gz"
      sha256 "9523dfb7d257c40c259c6c177d9aef504dec364ea0d3a6bd542275ee36ac2af2"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rapid7/icon-plugin-homebrew/releases/download/v4.11.6/icon-plugin_v4.11.6_Linux_x86_64.tar.gz"
      sha256 "4582818fd0fdf151b6d8c0f8ec4e66dba4c2e67883285e9d072317d608931e08"
    end
  end

  def install
    bin.install "icon-plugin"
  end

  test do
    system "#{bin}/icon-plugin --version"
  end
end
